
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="deliciouscuisine"
version="${file.jarVersion}"
displayName="Delicious Cuisine"
logoFile="delicious_cuisine.png"
credits="BDT"
authors="SenNan"
description=''' Food Mod: Enrich the original Minecraft missing food items'''

[[dependencies.deliciouscuisine]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

 [[dependencies.deliciouscuisine]]
    modId="minecraft"
    mandatory=true
  versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
